{% set name = "asap3" %}
{% set version = "3.11.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 242c782bf4267bf67001670f19e16d65f41cb5bf8161c4c7334863b516c52ad0

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openmpi
  host:
    - python
    - pip
    - numpy
    - openblas
    - openmpi
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ase
    - openblas

test:
  requires:
    - openmpi
  files:
    - Verlet*.pickle
    - hostfile
  source_files:
    - Test
  imports:
    - asap3
  commands:
    - cp Verlet*.pickle hostfile Test
    - cd Test
    - python TestAll.py
    - /usr/bin/sudo -n /usr/bin/yum -y -q install rsh  # [linux]
    - mpirun -np 2 --hostfile hostfile asap-python TestAll.py --parallel

about:
  home: https://wiki.fysik.dtu.dk/asap
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'ASAP is a calculator for doing large-scale classical molecular dynamics within ASE.'

  description: |
     ASAP is a tool for doing atomic-scale computer simulations
     (mainly molecular dynamics) using classical potentials
     (mainly Effective Medium Theory). It is intended to work 
     as an energy calculator in connection with the Atomic Simulation 
     Environment (ASE). However, some parts of the ASE are either 
     extended or reimplemented for reasons of efficiency and 
     ease-of-use on parallel computers.
  doc_url: https://wiki.fysik.dtu.dk/asap/Manual
  dev_url: https://gitlab.com/asap/asap

extra:
  recipe-maintainers:
    - jochym
