{% set name = "asap3" %}
{% set version = "3.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6c03c790ba4c9f0d231659078c26ce8193fa21314bf2fe4adaa7899d5cd9dbe
  #git_url: https://gitlab.com/asap/asap.git
  patches:
          #- bldlibrary.patch

build:
  number: 0
  #script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [not linux or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - openblas
    - openmpi
#    - {{ mpi }}  # [mpi != 'nompi']
    - kim-api
  run:
    - python
    - openblas
    - ase
    - {{ pin_compatible('numpy') }}
    - openmpi
#    - {{ mpi }}  # [mpi != 'nompi']    
    - kim-api

test:
  requires:
    #- {{ mpi }}  # [mpi != 'nompi']
    - openmpi
  files:
    - Verlet*.pickle
    - hostfile
  source_files:
    - Test
  imports:
    - asap3
  commands:
    - cp Verlet*.pickle hostfile Test
    - cd Test
    - python TestAll.py
    - mpirun -np 2 --hostfile hostfile python -W error::FutureWarning TestAll.py --parallel  # [mpi != 'nompi']

about:
  home: https://wiki.fysik.dtu.dk/asap
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'ASAP is a calculator for doing large-scale classical molecular dynamics within ASE.'

  description: |
     ASAP is a tool for doing atomic-scale computer simulations
     (mainly molecular dynamics) using classical potentials
     (mainly Effective Medium Theory). It is intended to work 
     as an energy calculator in connection with the Atomic Simulation 
     Environment (ASE). However, some parts of the ASE are either 
     extended or reimplemented for reasons of efficiency and 
     ease-of-use on parallel computers.
  doc_url: https://wiki.fysik.dtu.dk/asap/Manual
  dev_url: https://gitlab.com/asap/asap

extra:
  recipe-maintainers:
    - jochym
