{% set name = "asap3" %}
{% set version = "3.11.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: da1b9bb8cde76cf9010921dfd765acf8e7488ae60e5e57c62ec390a178c89261
  git_url: https://gitlab.com/asap/asap.git
  patches:
    - bldlibrary.patch

build:
  number: 4
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [not linux or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - openblas
    - {{ mpi }}  # [mpi != 'nompi']
    - kim-api
  run:
    - python
    - openblas
    - ase
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}  # [mpi != 'nompi']    
    - kim-api

test:
  requires:
    - {{ mpi }}  # [mpi != 'nompi']
  files:
    - Verlet*.pickle
    - hostfile
  source_files:
    - Test
  imports:
    - asap3
  commands:
    - cp Verlet*.pickle hostfile Test
    - cd Test
    - python TestAll.py
    - mpirun -np 2 --hostfile hostfile asap-python TestAll.py --parallel  # [mpi != 'nompi']

about:
  home: https://wiki.fysik.dtu.dk/asap
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'ASAP is a calculator for doing large-scale classical molecular dynamics within ASE.'

  description: |
     ASAP is a tool for doing atomic-scale computer simulations
     (mainly molecular dynamics) using classical potentials
     (mainly Effective Medium Theory). It is intended to work 
     as an energy calculator in connection with the Atomic Simulation 
     Environment (ASE). However, some parts of the ASE are either 
     extended or reimplemented for reasons of efficiency and 
     ease-of-use on parallel computers.
  doc_url: https://wiki.fysik.dtu.dk/asap/Manual
  dev_url: https://gitlab.com/asap/asap

extra:
  recipe-maintainers:
    - jochym
